<?php
/**
 * K2 Pickleball — One-Click Web Installer
 * 
 * Checks system requirements, collects configuration,
 * writes .env, runs schema + migrations + seed, then locks itself.
 * 
 * DELETE THIS FILE after installation for security.
 */

declare(strict_types=1);

// ─── Constants ───────────────────────────────────────────
define('K2_ROOT', dirname(__DIR__));
define('K2_LOCK', K2_ROOT . '/storage/.installed');
define('K2_ENV',  K2_ROOT . '/.env');

// ─── Already installed? ──────────────────────────────────
if (file_exists(K2_LOCK)) {
    http_response_code(403);
    echo '<!DOCTYPE html><html><head><title>Already Installed</title></head><body style="font-family:sans-serif;text-align:center;padding:60px"><h1>K2 Pickleball is already installed.</h1><p>Delete <code>public/install.php</code> for security.</p></body></html>';
    exit;
}

// ─── CSRF Token ──────────────────────────────────────────
session_start();
if (empty($_SESSION['install_csrf'])) {
    $_SESSION['install_csrf'] = bin2hex(random_bytes(32));
}
$csrf = $_SESSION['install_csrf'];

// ─── Helpers ─────────────────────────────────────────────
function checkRequirements(): array {
    $checks = [];
    
    // PHP version
    $checks[] = [
        'label' => 'PHP Version ≥ 8.2',
        'ok'    => version_compare(PHP_VERSION, '8.2.0', '>='),
        'value' => PHP_VERSION,
    ];
    
    // Required extensions
    $extensions = ['pdo', 'pdo_mysql', 'json', 'mbstring', 'openssl', 'fileinfo', 'curl', 'tokenizer'];
    foreach ($extensions as $ext) {
        $checks[] = [
            'label' => "ext-{$ext}",
            'ok'    => extension_loaded($ext),
            'value' => extension_loaded($ext) ? 'Loaded' : 'Missing',
        ];
    }
    
    // Writable directories
    $dirs = ['storage/cache', 'storage/logs', 'storage/uploads'];
    foreach ($dirs as $dir) {
        $full = K2_ROOT . '/' . $dir;
        $writable = is_dir($full) && is_writable($full);
        $checks[] = [
            'label' => "{$dir}/ writable",
            'ok'    => $writable,
            'value' => $writable ? 'Writable' : (is_dir($full) ? 'Not writable' : 'Missing'),
        ];
    }
    
    // Root writable (for .env)
    $checks[] = [
        'label' => 'Project root writable (for .env)',
        'ok'    => is_writable(K2_ROOT),
        'value' => is_writable(K2_ROOT) ? 'Writable' : 'Not writable',
    ];
    
    // Vendor autoload
    $checks[] = [
        'label' => 'Composer dependencies installed',
        'ok'    => file_exists(K2_ROOT . '/vendor/autoload.php'),
        'value' => file_exists(K2_ROOT . '/vendor/autoload.php') ? 'Found' : 'Run: composer install',
    ];
    
    // Schema file
    $checks[] = [
        'label' => 'database/schema.sql exists',
        'ok'    => file_exists(K2_ROOT . '/database/schema.sql'),
        'value' => file_exists(K2_ROOT . '/database/schema.sql') ? 'Found' : 'Missing',
    ];
    
    return $checks;
}

function allRequirementsMet(array $checks): bool {
    foreach ($checks as $c) {
        if (!$c['ok']) return false;
    }
    return true;
}

function generateJwtSecret(): string {
    return bin2hex(random_bytes(32)); // 64 hex chars
}

function generateAppKey(): string {
    return 'base64:' . base64_encode(random_bytes(32));
}

function testDbConnection(string $host, string $port, string $user, string $pass, string $dbName): array {
    try {
        $dsn = "mysql:host={$host};port={$port};charset=utf8mb4";
        $pdo = new PDO($dsn, $user, $pass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 5,
            PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
        ]);
        // Try to create the database
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `{$dbName}`");
        return ['ok' => true, 'pdo' => $pdo];
    } catch (PDOException $e) {
        return ['ok' => false, 'error' => $e->getMessage()];
    }
}

function writeEnvFile(array $data): bool {
    $env = <<<ENV
# ============================================
# K2 Pickleball SaaS Platform
# Generated by Installer on {$data['_date']}
# ============================================

# Application
APP_NAME="{$data['app_name']}"
APP_ENV=production
APP_DEBUG=false
APP_URL={$data['app_url']}
APP_TIMEZONE={$data['app_timezone']}
APP_KEY={$data['app_key']}

# Database
DB_HOST={$data['db_host']}
DB_PORT={$data['db_port']}
DB_NAME={$data['db_name']}
DB_USER={$data['db_user']}
DB_PASS={$data['db_pass']}
DB_CHARSET=utf8mb4

# JWT Authentication
JWT_SECRET={$data['jwt_secret']}
JWT_ALGO=HS256
JWT_ACCESS_TTL=1800
JWT_REFRESH_TTL=2592000

# Google OAuth (get from https://console.cloud.google.com/)
GOOGLE_CLIENT_ID={$data['google_client_id']}
GOOGLE_CLIENT_SECRET={$data['google_client_secret']}

# Square Payments
SQUARE_ENVIRONMENT={$data['square_environment']}
SQUARE_ACCESS_TOKEN={$data['square_access_token']}
SQUARE_APPLICATION_ID={$data['square_app_id']}
SQUARE_LOCATION_ID={$data['square_location_id']}
SQUARE_WEBHOOK_SIGNATURE_KEY={$data['square_webhook_key']}

# Redis (optional)
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_PREFIX=k2pb_

# File Storage
STORAGE_DISK=local
STORAGE_PATH=storage/uploads
MAX_UPLOAD_SIZE=10485760

# Mail
MAIL_DRIVER=smtp
MAIL_HOST={$data['mail_host']}
MAIL_PORT={$data['mail_port']}
MAIL_USERNAME={$data['mail_user']}
MAIL_PASSWORD={$data['mail_pass']}
MAIL_FROM_ADDRESS={$data['mail_from']}
MAIL_FROM_NAME="{$data['app_name']}"

# Rate Limiting
RATE_LIMIT_DEFAULT=60
RATE_LIMIT_AUTH=5
RATE_LIMIT_FORMS=3
RATE_LIMIT_WINDOW=60

# Logging
LOG_LEVEL=error
LOG_PATH=storage/logs

# Slack Notifications
SLACK_WEBHOOK_URL={$data['slack_webhook_url']}

# Domain Configuration
PLATFORM_DOMAIN={$data['platform_domain']}
ADMIN_DOMAIN={$data['admin_domain']}
API_DOMAIN={$data['api_domain']}
BASE_DOMAIN={$data['base_domain']}
ENV;

    return (bool) file_put_contents(K2_ENV, $env, LOCK_EX);
}

function runSchema(PDO $pdo): array {
    $log = [];
    $schemaFile = K2_ROOT . '/database/schema.sql';
    $sql = file_get_contents($schemaFile);
    
    // Remove comments and split
    $sql = preg_replace('/--[^\n]*\n/', "\n", $sql);
    $statements = array_filter(array_map('trim', explode(';', $sql)), fn($s) => !empty($s));
    
    $ok = 0;
    $skip = 0;
    $errors = 0;
    foreach ($statements as $stmt) {
        try {
            $pdo->exec($stmt);
            $ok++;
            if (preg_match('/CREATE TABLE\s+(?:IF NOT EXISTS\s+)?`?(\w+)`?/i', $stmt, $m)) {
                $log[] = ['ok', "Created table: {$m[1]}"];
            }
        } catch (PDOException $e) {
            if (str_contains($e->getMessage(), 'already exists')) {
                $skip++;
            } else {
                $errors++;
                $log[] = ['error', $e->getMessage()];
            }
        }
    }
    $log[] = ['info', "Schema: {$ok} executed, {$skip} skipped, {$errors} errors"];
    return $log;
}

function runMigrations(PDO $pdo, string $host, string $port, string $user, string $pass, string $dbName): array {
    $log = [];
    $migrationsDir = K2_ROOT . '/database/migrations';
    
    if (!is_dir($migrationsDir)) {
        $log[] = ['warn', 'No migrations directory found — skipping'];
        return $log;
    }
    
    $files = glob($migrationsDir . '/*.sql');
    if (empty($files)) {
        $log[] = ['info', 'No migration files found'];
        return $log;
    }
    
    // Sort files naturally (001_, 002_, ..., then alphabetic for unnumbered)
    usort($files, function($a, $b) {
        $aBase = basename($a);
        $bBase = basename($b);
        $aNum = preg_match('/^(\d+)_/', $aBase, $am) ? (int)$am[1] : 9999;
        $bNum = preg_match('/^(\d+)_/', $bBase, $bm) ? (int)$bm[1] : 9999;
        if ($aNum !== $bNum) return $aNum - $bNum;
        return strcmp($aBase, $bBase);
    });
    
    // Use mysqli for multi_query support (handles SET @var, PREPARE/EXECUTE patterns)
    // Disable mysqli exception throwing so we can handle errors gracefully
    mysqli_report(MYSQLI_REPORT_OFF);
    
    $mysqli = new mysqli($host, $user, $pass, $dbName, (int)$port);
    if ($mysqli->connect_error) {
        $log[] = ['error', 'mysqli connect failed: ' . $mysqli->connect_error];
        return $log;
    }
    $mysqli->set_charset('utf8mb4');
    
    $ok = 0;
    $errors = 0;
    foreach ($files as $file) {
        $filename = basename($file);
        if ($filename === '.gitkeep' || str_starts_with($filename, '_')) continue;
        
        $sql = file_get_contents($file);
        // Strip single-line comments but preserve the SQL structure
        $sql = preg_replace('/--[^\n]*/', '', $sql);
        $sql = trim($sql);
        if (empty($sql)) continue;
        
        $fileOk = true;
        $fileErrors = [];
        
        try {
            $queryOk = $mysqli->multi_query($sql);
            if ($queryOk) {
                // Consume all result sets, checking each for errors
                do {
                    if ($result = $mysqli->store_result()) {
                        $result->free();
                    }
                    if ($mysqli->errno && !isIgnorableMigrationError($mysqli->error)) {
                        $fileOk = false;
                        $fileErrors[] = $mysqli->error;
                    }
                } while ($mysqli->more_results() && $mysqli->next_result());
            }
            
            // Check final error state
            if ($mysqli->errno && !isIgnorableMigrationError($mysqli->error)) {
                $fileOk = false;
                if (!in_array($mysqli->error, $fileErrors, true)) {
                    $fileErrors[] = $mysqli->error;
                }
            }
        } catch (\Throwable $e) {
            // Catch any mysqli exceptions that slip through
            $msg = $e->getMessage();
            if (!isIgnorableMigrationError($msg)) {
                $fileOk = false;
                $fileErrors[] = $msg;
            }
            // Drain remaining results so connection is clean
            while ($mysqli->more_results() && $mysqli->next_result()) {
                if ($result = $mysqli->store_result()) {
                    $result->free();
                }
            }
        }
        
        $ok++;
        if ($fileOk) {
            $log[] = ['ok', "Migration: {$filename}"];
        } else {
            $errors += count($fileErrors);
            foreach ($fileErrors as $err) {
                $log[] = ['error', "{$filename}: {$err}"];
            }
        }
    }
    
    $mysqli->close();
    $log[] = ['info', "Migrations: {$ok} files processed, {$errors} errors"];
    return $log;
}

function isIgnorableMigrationError(string $msg): bool {
    $patterns = [
        'already exists',
        'Duplicate column',
        'Duplicate entry',
        'Duplicate key',
        "Can't DROP",
        'Unknown column',
        'Column not found',
        'check that it exists',
        "doesn't exist",
        'Table already exists',
        'Foreign key constraint is incorrectly formed',
    ];
    foreach ($patterns as $p) {
        if (str_contains($msg, $p)) return true;
    }
    return false;
}

function runSeeder(PDO $pdo, string $adminEmail, string $adminPassword): array {
    $log = [];
    
    try {
        // ── Permissions ──
        $permissions = [
            ['View Organizations', 'organizations.view', 'organizations'],
            ['Create Organizations', 'organizations.create', 'organizations'],
            ['Update Organizations', 'organizations.update', 'organizations'],
            ['Delete Organizations', 'organizations.delete', 'organizations'],
            ['View Facilities', 'facilities.view', 'facilities'],
            ['Create Facilities', 'facilities.create', 'facilities'],
            ['Update Facilities', 'facilities.update', 'facilities'],
            ['Delete Facilities', 'facilities.delete', 'facilities'],
            ['View Courts', 'courts.view', 'courts'],
            ['Create Courts', 'courts.create', 'courts'],
            ['Update Courts', 'courts.update', 'courts'],
            ['Delete Courts', 'courts.delete', 'courts'],
            ['View Users', 'users.view', 'users'],
            ['Create Users', 'users.create', 'users'],
            ['Update Users', 'users.update', 'users'],
            ['Delete Users', 'users.delete', 'users'],
            ['View Roles', 'roles.view', 'roles'],
            ['Create Roles', 'roles.create', 'roles'],
            ['Update Roles', 'roles.update', 'roles'],
            ['Delete Roles', 'roles.delete', 'roles'],
            ['View Subscriptions', 'subscriptions.view', 'subscriptions'],
            ['Manage Subscriptions', 'subscriptions.manage', 'subscriptions'],
            ['View Payments', 'payments.view', 'payments'],
            ['Process Payments', 'payments.process', 'payments'],
            ['Manage Payment Methods', 'payments.methods', 'payments'],
            ['View Files', 'files.view', 'files'],
            ['Upload Files', 'files.upload', 'files'],
            ['Delete Files', 'files.delete', 'files'],
            ['View Settings', 'settings.view', 'settings'],
            ['Update Settings', 'settings.update', 'settings'],
            ['View Audit Logs', 'audit-logs.view', 'audit-logs'],
            ['Manage API Tokens', 'api-tokens.manage', 'api-tokens'],
            ['View Notifications', 'notifications.view', 'notifications'],
            ['Manage Notifications', 'notifications.manage', 'notifications'],
        ];
        
        $stmt = $pdo->prepare("INSERT IGNORE INTO permissions (name, slug, module, description, created_at) VALUES (:name, :slug, :module, :name, NOW())");
        foreach ($permissions as [$name, $slug, $module]) {
            $stmt->execute(['name' => $name, 'slug' => $slug, 'module' => $module]);
        }
        $log[] = ['ok', count($permissions) . ' permissions seeded'];
        
        // ── Roles ──
        $roles = [
            ['Super Admin', 'super-admin', 'Platform super administrator', 1, '*'],
            ['Organization Owner', 'org-owner', 'Organization owner with full org access', 1, '*'],
            ['Organization Admin', 'org-admin', 'Organization administrator', 1, 'organizations.view,organizations.update,facilities.view,facilities.create,facilities.update,facilities.delete,courts.view,courts.create,courts.update,courts.delete,users.view,users.create,users.update,roles.view,subscriptions.view,payments.view,payments.process,payments.methods,files.view,files.upload,files.delete,settings.view,settings.update,audit-logs.view,api-tokens.manage,notifications.view,notifications.manage'],
            ['Facility Manager', 'facility-manager', 'Manages facility operations', 1, 'facilities.view,facilities.update,courts.view,courts.create,courts.update,users.view,files.view,files.upload,notifications.view'],
            ['Staff', 'staff', 'Staff member with limited access', 1, 'facilities.view,courts.view,users.view,notifications.view,files.view'],
            ['Player', 'player', 'Registered player', 1, 'facilities.view,courts.view,notifications.view'],
            ['Guest', 'guest', 'Guest with read-only access', 1, 'facilities.view,courts.view'],
        ];
        
        $allPerms = $pdo->query("SELECT id, slug FROM permissions")->fetchAll(PDO::FETCH_ASSOC);
        $permMap = array_column($allPerms, 'id', 'slug');
        
        $roleStmt = $pdo->prepare("INSERT IGNORE INTO roles (name, slug, description, is_system, created_at, updated_at) VALUES (:name, :slug, :desc, :sys, NOW(), NOW())");
        $rpStmt = $pdo->prepare("INSERT IGNORE INTO role_permissions (role_id, permission_id) VALUES (:rid, :pid)");
        
        foreach ($roles as [$name, $slug, $desc, $sys, $perms]) {
            $roleStmt->execute(['name' => $name, 'slug' => $slug, 'desc' => $desc, 'sys' => $sys]);
            $roleId = $pdo->query("SELECT id FROM roles WHERE slug = " . $pdo->quote($slug))->fetchColumn();
            if (!$roleId) continue;
            
            $permSlugs = ($perms === '*') ? array_keys($permMap) : explode(',', $perms);
            foreach ($permSlugs as $ps) {
                if (isset($permMap[$ps])) {
                    $rpStmt->execute(['rid' => $roleId, 'pid' => $permMap[$ps]]);
                }
            }
        }
        $log[] = ['ok', count($roles) . ' roles seeded'];
        
        // ── Super Admin User ──
        $exists = $pdo->query("SELECT id FROM users WHERE email = " . $pdo->quote($adminEmail))->fetchColumn();
        if (!$exists) {
            $uuid = sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
                random_int(0, 0xffff), random_int(0, 0xffff), random_int(0, 0xffff),
                random_int(0, 0x0fff) | 0x4000, random_int(0, 0x3fff) | 0x8000,
                random_int(0, 0xffff), random_int(0, 0xffff), random_int(0, 0xffff));
            $hash = password_hash($adminPassword, PASSWORD_BCRYPT, ['cost' => 12]);
            
            $pdo->prepare("INSERT INTO users (uuid, first_name, last_name, email, password_hash, status, email_verified_at, created_at, updated_at) VALUES (:uuid, 'Super', 'Admin', :email, :hash, 'active', NOW(), NOW(), NOW())")
                ->execute(['uuid' => $uuid, 'email' => $adminEmail, 'hash' => $hash]);
            $log[] = ['ok', "Super admin created: {$adminEmail}"];
        } else {
            $log[] = ['info', "Super admin already exists: {$adminEmail}"];
        }
        
        // ── Subscription Plans ──
        $plans = [
            ['Free', 'free', 'Get started with basic features', 0, 0, 1, 4, 10, 1, 1],
            ['Professional', 'professional', 'Everything you need', 49.99, 499.99, 5, 20, 100, 1, 2],
            ['Enterprise', 'enterprise', 'For large organizations', 149.99, 1499.99, null, null, null, 1, 3],
        ];
        $planStmt = $pdo->prepare("INSERT IGNORE INTO plans (name, slug, description, price_monthly, price_yearly, max_facilities, max_courts, max_users, is_active, sort_order, created_at, updated_at) VALUES (:n, :s, :d, :pm, :py, :mf, :mc, :mu, :ia, :so, NOW(), NOW())");
        foreach ($plans as [$n, $s, $d, $pm, $py, $mf, $mc, $mu, $ia, $so]) {
            $planStmt->execute(['n'=>$n, 's'=>$s, 'd'=>$d, 'pm'=>$pm, 'py'=>$py, 'mf'=>$mf, 'mc'=>$mc, 'mu'=>$mu, 'ia'=>$ia, 'so'=>$so]);
        }
        $log[] = ['ok', '3 subscription plans seeded'];
        
        // ── Default Settings ──
        $settings = [
            ['general', 'app_name', 'K2 Pickleball', 'string'],
            ['general', 'app_description', 'Sports Facility & Club Management Platform', 'string'],
            ['general', 'default_timezone', 'America/New_York', 'string'],
            ['general', 'default_currency', 'USD', 'string'],
            ['general', 'default_locale', 'en_US', 'string'],
            ['branding', 'primary_color', '#3b82f6', 'string'],
            ['branding', 'logo_url', '', 'string'],
            ['notifications', 'email_enabled', '1', 'boolean'],
            ['notifications', 'sms_enabled', '0', 'boolean'],
            ['billing', 'tax_rate', '0', 'float'],
            ['billing', 'trial_days', '14', 'integer'],
            ['billing', 'grace_period_days', '7', 'integer'],
        ];
        $settingStmt = $pdo->prepare("INSERT IGNORE INTO settings (organization_id, `group_name`, `key_name`, value, type, created_at, updated_at) VALUES (NULL, :g, :k, :v, :t, NOW(), NOW())");
        foreach ($settings as [$g, $k, $v, $t]) {
            $settingStmt->execute(['g'=>$g, 'k'=>$k, 'v'=>$v, 't'=>$t]);
        }
        $log[] = ['ok', count($settings) . ' default settings seeded'];
        
    } catch (PDOException $e) {
        $log[] = ['error', 'Seed error: ' . $e->getMessage()];
    }
    
    return $log;
}

// ─── Handle POST (Installation) ─────────────────────────
$step = 'form'; // form | installing | done
$installLog = [];
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // CSRF check
    if (!isset($_POST['_csrf']) || !hash_equals($csrf, $_POST['_csrf'])) {
        $error = 'Invalid security token. Please refresh and try again.';
    } else {
        $step = 'installing';
        
        // Collect & sanitize input
        $data = [
            'app_name'        => trim($_POST['app_name'] ?? 'K2 Pickleball'),
            'app_url'         => rtrim(trim($_POST['app_url'] ?? ''), '/'),
            'app_timezone'    => trim($_POST['app_timezone'] ?? 'America/New_York'),
            'base_domain'     => trim($_POST['base_domain'] ?? ''),
            'platform_domain' => trim($_POST['platform_domain'] ?? ''),
            'admin_domain'    => trim($_POST['admin_domain'] ?? ''),
            'api_domain'      => trim($_POST['api_domain'] ?? ''),
            'db_host'         => trim($_POST['db_host'] ?? '127.0.0.1'),
            'db_port'         => trim($_POST['db_port'] ?? '3306'),
            'db_name'         => trim($_POST['db_name'] ?? 'k2pickleball'),
            'db_user'         => trim($_POST['db_user'] ?? 'root'),
            'db_pass'         => $_POST['db_pass'] ?? '',
            'admin_email'     => trim($_POST['admin_email'] ?? ''),
            'admin_password'  => $_POST['admin_password'] ?? '',
            'mail_host'       => trim($_POST['mail_host'] ?? ''),
            'mail_port'       => trim($_POST['mail_port'] ?? '587'),
            'mail_user'       => trim($_POST['mail_user'] ?? ''),
            'mail_pass'       => $_POST['mail_pass'] ?? '',
            'mail_from'       => trim($_POST['mail_from'] ?? 'noreply@k2pickleball.com'),
            // Google OAuth
            'google_client_id'     => trim($_POST['google_client_id'] ?? ''),
            'google_client_secret' => trim($_POST['google_client_secret'] ?? ''),
            // Square Payments
            'square_environment'   => trim($_POST['square_environment'] ?? 'sandbox'),
            'square_access_token'  => trim($_POST['square_access_token'] ?? ''),
            'square_app_id'        => trim($_POST['square_app_id'] ?? ''),
            'square_location_id'   => trim($_POST['square_location_id'] ?? ''),
            'square_webhook_key'   => trim($_POST['square_webhook_key'] ?? ''),
            // Slack
            'slack_webhook_url'    => trim($_POST['slack_webhook_url'] ?? ''),
        ];
        
        // Validate required
        if (empty($data['base_domain']) || empty($data['admin_email']) || empty($data['admin_password'])) {
            $error = 'Base domain, admin email, and admin password are required.';
            $step = 'form';
        }
        
        if (strlen($data['admin_password']) < 8) {
            $error = 'Admin password must be at least 8 characters.';
            $step = 'form';
        }
        
        if (!filter_var($data['admin_email'], FILTER_VALIDATE_EMAIL)) {
            $error = 'Please enter a valid admin email address.';
            $step = 'form';
        }
        
        if ($step === 'installing') {
            // Step 1: Test DB
            $installLog[] = ['info', '── Step 1: Testing database connection...'];
            $dbResult = testDbConnection($data['db_host'], $data['db_port'], $data['db_user'], $data['db_pass'], $data['db_name']);
            
            if (!$dbResult['ok']) {
                $installLog[] = ['error', 'Database connection failed: ' . $dbResult['error']];
                $step = 'form';
                $error = 'Database connection failed: ' . $dbResult['error'];
            } else {
                $pdo = $dbResult['pdo'];
                $installLog[] = ['ok', 'Database connected successfully'];
                
                // Step 2: Write .env
                $installLog[] = ['info', '── Step 2: Writing .env file...'];
                $data['jwt_secret'] = generateJwtSecret();
                $data['app_key'] = generateAppKey();
                $data['_date'] = date('Y-m-d H:i:s');
                
                if (writeEnvFile($data)) {
                    $installLog[] = ['ok', '.env file created'];
                } else {
                    $installLog[] = ['error', 'Failed to write .env — check file permissions'];
                    $step = 'form';
                    $error = 'Failed to write .env file. Check permissions on the project root.';
                }
            }
        }
        
        if ($step === 'installing') {
            // Step 3: Run schema
            $installLog[] = ['info', '── Step 3: Running database schema...'];
            $schemaLog = runSchema($pdo);
            $installLog = array_merge($installLog, $schemaLog);
            
            // Step 4: Run migrations
            $installLog[] = ['info', '── Step 4: Running migrations...'];
            $migLog = runMigrations($pdo, $data['db_host'], $data['db_port'], $data['db_user'], $data['db_pass'], $data['db_name']);
            $installLog = array_merge($installLog, $migLog);
            
            // Step 5: Seed data
            $installLog[] = ['info', '── Step 5: Seeding database...'];
            $seedLog = runSeeder($pdo, $data['admin_email'], $data['admin_password']);
            $installLog = array_merge($installLog, $seedLog);
            
            // Step 6: Create lock file
            $lockData = json_encode([
                'installed_at' => date('c'),
                'php_version'  => PHP_VERSION,
                'admin_email'  => $data['admin_email'],
            ]);
            file_put_contents(K2_LOCK, $lockData, LOCK_EX);
            $installLog[] = ['ok', 'Installation lock created'];
            
            // Step 7: create storage subdirs if missing
            foreach (['storage/cache', 'storage/logs', 'storage/uploads'] as $dir) {
                $full = K2_ROOT . '/' . $dir;
                if (!is_dir($full)) {
                    mkdir($full, 0775, true);
                }
            }
            
            $step = 'done';
            $installLog[] = ['info', '── Installation complete!'];
        }
    }
}

$checks = checkRequirements();
$allMet = allRequirementsMet($checks);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>K2 Pickleball — Installer</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%); min-height: 100vh; }
        .glass { background: rgba(30, 41, 59, 0.8); backdrop-filter: blur(12px); border: 1px solid rgba(148, 163, 184, 0.1); }
        .step-card { transition: all 0.3s ease; }
        .log-ok { color: #4ade80; }
        .log-error { color: #f87171; }
        .log-warn { color: #fbbf24; }
        .log-info { color: #60a5fa; }
        input, select { transition: border-color 0.2s; }
        input:focus, select:focus { border-color: #3b82f6 !important; outline: none; box-shadow: 0 0 0 3px rgba(59,130,246,0.2); }
    </style>
</head>
<body class="text-gray-200 antialiased">
    <div class="max-w-3xl mx-auto px-4 py-12">
        
        <!-- Header -->
        <div class="text-center mb-10">
            <div class="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-blue-500/20 border border-blue-500/30 mb-4">
                <svg class="w-8 h-8 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z"/>
                </svg>
            </div>
            <h1 class="text-3xl font-bold text-white">K2 Pickleball</h1>
            <p class="text-gray-400 mt-1">Platform Installer</p>
        </div>

        <?php if ($step === 'done'): ?>
        <!-- ═══════════════ DONE ═══════════════ -->
        <div class="glass rounded-2xl p-8">
            <div class="text-center mb-6">
                <div class="inline-flex items-center justify-center w-20 h-20 rounded-full bg-green-500/20 border border-green-500/30 mb-4">
                    <svg class="w-10 h-10 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
                    </svg>
                </div>
                <h2 class="text-2xl font-bold text-white">Installation Complete!</h2>
                <p class="text-gray-400 mt-2">Your K2 Pickleball platform is ready to use.</p>
            </div>
            
            <!-- Install Log -->
            <div class="bg-gray-900/60 rounded-xl p-4 mb-6 max-h-64 overflow-y-auto font-mono text-sm">
                <?php foreach ($installLog as [$type, $msg]): ?>
                    <div class="log-<?= $type ?> py-0.5">
                        <?php if ($type === 'ok'): ?>✅<?php elseif ($type === 'error'): ?>❌<?php elseif ($type === 'warn'): ?>⚠️<?php else: ?>ℹ️<?php endif; ?>
                        <?= htmlspecialchars($msg, ENT_QUOTES, 'UTF-8') ?>
                    </div>
                <?php endforeach; ?>
            </div>
            
            <!-- Quick Links -->
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
                <a href="<?= htmlspecialchars($_POST['app_url'] ?? '/', ENT_QUOTES, 'UTF-8') ?>" class="flex items-center gap-3 p-4 rounded-xl bg-blue-500/10 border border-blue-500/20 hover:bg-blue-500/20 transition">
                    <svg class="w-5 h-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-4 0h4"/></svg>
                    <div>
                        <div class="text-white font-medium">Visit Site</div>
                        <div class="text-xs text-gray-400">Main website</div>
                    </div>
                </a>
                <a href="https://<?= htmlspecialchars($_POST['platform_domain'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="flex items-center gap-3 p-4 rounded-xl bg-purple-500/10 border border-purple-500/20 hover:bg-purple-500/20 transition">
                    <svg class="w-5 h-5 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/></svg>
                    <div>
                        <div class="text-white font-medium">Platform Admin</div>
                        <div class="text-xs text-gray-400">Super admin panel</div>
                    </div>
                </a>
            </div>
            
            <div class="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-4 text-sm text-yellow-300">
                <strong>⚠️ Security:</strong> Delete <code class="bg-yellow-500/20 px-1.5 py-0.5 rounded text-yellow-200">public/install.php</code> from your server immediately.
            </div>
            
            <div class="mt-4 bg-gray-800/50 rounded-xl p-4 text-sm text-gray-300">
                <strong>Admin Login:</strong><br>
                Email: <code class="text-blue-300"><?= htmlspecialchars($_POST['admin_email'] ?? '', ENT_QUOTES, 'UTF-8') ?></code><br>
                Password: <em>the password you entered</em>
            </div>
        </div>

        <?php else: ?>
        <!-- ═══════════════ REQUIREMENTS + FORM ═══════════════ -->
        
        <!-- System Requirements -->
        <div class="glass rounded-2xl p-6 mb-6">
            <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <svg class="w-5 h-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                System Requirements
            </h2>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <?php foreach ($checks as $c): ?>
                <div class="flex items-center gap-2 py-1.5 px-3 rounded-lg <?= $c['ok'] ? 'bg-green-500/10' : 'bg-red-500/10' ?>">
                    <?php if ($c['ok']): ?>
                        <svg class="w-4 h-4 text-green-400 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
                    <?php else: ?>
                        <svg class="w-4 h-4 text-red-400 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                    <?php endif; ?>
                    <span class="text-sm <?= $c['ok'] ? 'text-green-300' : 'text-red-300' ?>"><?= htmlspecialchars($c['label'], ENT_QUOTES, 'UTF-8') ?></span>
                    <span class="text-xs text-gray-500 ml-auto"><?= htmlspecialchars($c['value'], ENT_QUOTES, 'UTF-8') ?></span>
                </div>
                <?php endforeach; ?>
            </div>
            <?php if (!$allMet): ?>
            <div class="mt-4 bg-red-500/10 border border-red-500/20 rounded-xl p-3 text-sm text-red-300">
                ⚠️ Some requirements are not met. Please fix them before proceeding.
            </div>
            <?php endif; ?>
        </div>
        
        <?php if ($error): ?>
        <div class="glass rounded-2xl p-4 mb-6 border-red-500/30 bg-red-500/10">
            <p class="text-red-300 text-sm">❌ <?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p>
        </div>
        <?php endif; ?>
        
        <!-- Installation Log (if partial fail) -->
        <?php if (!empty($installLog)): ?>
        <div class="glass rounded-2xl p-4 mb-6">
            <h3 class="text-sm font-semibold text-gray-400 mb-2">Installation Log</h3>
            <div class="bg-gray-900/60 rounded-xl p-3 max-h-40 overflow-y-auto font-mono text-xs">
                <?php foreach ($installLog as [$type, $msg]): ?>
                    <div class="log-<?= $type ?> py-0.5"><?= htmlspecialchars($msg, ENT_QUOTES, 'UTF-8') ?></div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php endif; ?>
        
        <!-- Configuration Form -->
        <form method="POST" class="space-y-6" <?= !$allMet ? 'style="opacity:0.5;pointer-events:none"' : '' ?>>
            <input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrf, ENT_QUOTES, 'UTF-8') ?>">
            
            <!-- Database -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-blue-500/20 text-blue-400 text-sm font-bold">1</span>
                    Database Configuration
                </h2>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Database Host</label>
                        <input type="text" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? '127.0.0.1', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required>
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Port</label>
                        <input type="text" name="db_port" value="<?= htmlspecialchars($_POST['db_port'] ?? '3306', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required>
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Database Name</label>
                        <input type="text" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? 'k2pickleball', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required>
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Database User</label>
                        <input type="text" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? 'root', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required>
                    </div>
                    <div class="sm:col-span-2">
                        <label class="block text-sm text-gray-400 mb-1">Database Password</label>
                        <input type="password" name="db_pass" value="" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="Leave blank if none">
                    </div>
                </div>
            </div>
            
            <!-- Domain -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-blue-500/20 text-blue-400 text-sm font-bold">2</span>
                    Domain Configuration
                </h2>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div class="sm:col-span-2">
                        <label class="block text-sm text-gray-400 mb-1">Application URL</label>
                        <input type="url" name="app_url" value="<?= htmlspecialchars($_POST['app_url'] ?? 'https://k2pickleball.com', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required placeholder="https://k2pickleball.com">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Base Domain <span class="text-red-400">*</span></label>
                        <input type="text" name="base_domain" value="<?= htmlspecialchars($_POST['base_domain'] ?? 'k2pickleball.com', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required placeholder="k2pickleball.com">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Platform Domain</label>
                        <input type="text" name="platform_domain" value="<?= htmlspecialchars($_POST['platform_domain'] ?? 'platform.k2pickleball.com', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required>
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Admin Domain</label>
                        <input type="text" name="admin_domain" value="<?= htmlspecialchars($_POST['admin_domain'] ?? 'admin.k2pickleball.com', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required>
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">API Domain</label>
                        <input type="text" name="api_domain" value="<?= htmlspecialchars($_POST['api_domain'] ?? 'api.k2pickleball.com', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required>
                    </div>
                </div>
            </div>
            
            <!-- Admin Account -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-blue-500/20 text-blue-400 text-sm font-bold">3</span>
                    Super Admin Account
                </h2>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Admin Email <span class="text-red-400">*</span></label>
                        <input type="email" name="admin_email" value="<?= htmlspecialchars($_POST['admin_email'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required placeholder="admin@k2pickleball.com">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Admin Password <span class="text-red-400">*</span></label>
                        <input type="password" name="admin_password" value="" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" required minlength="8" placeholder="Min 8 characters">
                    </div>
                </div>
            </div>
            
            <!-- App Settings -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-blue-500/20 text-blue-400 text-sm font-bold">4</span>
                    Application Settings
                </h2>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">App Name</label>
                        <input type="text" name="app_name" value="<?= htmlspecialchars($_POST['app_name'] ?? 'K2 Pickleball', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Timezone</label>
                        <select name="app_timezone" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm">
                            <?php 
                            $timezones = ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles', 'America/Phoenix', 'America/Anchorage', 'Pacific/Honolulu', 'UTC', 'Europe/London', 'Europe/Paris', 'Asia/Dubai', 'Asia/Kolkata', 'Asia/Shanghai', 'Asia/Tokyo', 'Australia/Sydney'];
                            $selected = $_POST['app_timezone'] ?? 'America/New_York';
                            foreach ($timezones as $tz): ?>
                                <option value="<?= $tz ?>" <?= $tz === $selected ? 'selected' : '' ?>><?= $tz ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
            
            <!-- Google OAuth (Optional) -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-gray-600/40 text-gray-400 text-sm font-bold">5</span>
                    Google OAuth <span class="text-xs text-gray-500 ml-2">(Optional — for Google Sign-In)</span>
                </h2>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div class="sm:col-span-2">
                        <label class="block text-sm text-gray-400 mb-1">Google Client ID</label>
                        <input type="text" name="google_client_id" value="<?= htmlspecialchars($_POST['google_client_id'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="xxxx.apps.googleusercontent.com">
                    </div>
                    <div class="sm:col-span-2">
                        <label class="block text-sm text-gray-400 mb-1">Google Client Secret</label>
                        <input type="password" name="google_client_secret" value="<?= htmlspecialchars($_POST['google_client_secret'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="GOCSPX-...">
                    </div>
                </div>
            </div>

            <!-- Square Payments (Optional) -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-gray-600/40 text-gray-400 text-sm font-bold">6</span>
                    Square Payments <span class="text-xs text-gray-500 ml-2">(Optional — configure later in .env)</span>
                </h2>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Environment</label>
                        <select name="square_environment" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm">
                            <option value="sandbox" <?= ($_POST['square_environment'] ?? 'sandbox') === 'sandbox' ? 'selected' : '' ?>>Sandbox</option>
                            <option value="production" <?= ($_POST['square_environment'] ?? '') === 'production' ? 'selected' : '' ?>>Production</option>
                        </select>
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Location ID</label>
                        <input type="text" name="square_location_id" value="<?= htmlspecialchars($_POST['square_location_id'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="L...">
                    </div>
                    <div class="sm:col-span-2">
                        <label class="block text-sm text-gray-400 mb-1">Access Token</label>
                        <input type="password" name="square_access_token" value="<?= htmlspecialchars($_POST['square_access_token'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="EAAAl...">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Application ID</label>
                        <input type="text" name="square_app_id" value="<?= htmlspecialchars($_POST['square_app_id'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="sandbox-sq0idb-...">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">Webhook Signature Key</label>
                        <input type="text" name="square_webhook_key" value="<?= htmlspecialchars($_POST['square_webhook_key'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="Optional">
                    </div>
                </div>
            </div>

            <!-- Slack (Optional) -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-gray-600/40 text-gray-400 text-sm font-bold">7</span>
                    Slack Notifications <span class="text-xs text-gray-500 ml-2">(Optional)</span>
                </h2>
                <div>
                    <label class="block text-sm text-gray-400 mb-1">Slack Webhook URL</label>
                    <input type="url" name="slack_webhook_url" value="<?= htmlspecialchars($_POST['slack_webhook_url'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="https://hooks.slack.com/services/...">
                </div>
            </div>

            <!-- Mail (Optional) -->
            <div class="glass rounded-2xl p-6 step-card">
                <h2 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                    <span class="inline-flex items-center justify-center w-7 h-7 rounded-full bg-gray-600/40 text-gray-400 text-sm font-bold">8</span>
                    Mail Settings <span class="text-xs text-gray-500 ml-2">(Optional — configure later in .env)</span>
                </h2>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">SMTP Host</label>
                        <input type="text" name="mail_host" value="<?= htmlspecialchars($_POST['mail_host'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm" placeholder="smtp.gmail.com">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">SMTP Port</label>
                        <input type="text" name="mail_port" value="<?= htmlspecialchars($_POST['mail_port'] ?? '587', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">SMTP Username</label>
                        <input type="text" name="mail_user" value="<?= htmlspecialchars($_POST['mail_user'] ?? '', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm">
                    </div>
                    <div>
                        <label class="block text-sm text-gray-400 mb-1">SMTP Password</label>
                        <input type="password" name="mail_pass" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm">
                    </div>
                    <div class="sm:col-span-2">
                        <label class="block text-sm text-gray-400 mb-1">From Address</label>
                        <input type="email" name="mail_from" value="<?= htmlspecialchars($_POST['mail_from'] ?? 'noreply@k2pickleball.com', ENT_QUOTES, 'UTF-8') ?>" class="w-full bg-gray-900/60 border border-gray-700 rounded-lg px-3 py-2 text-white text-sm">
                    </div>
                </div>
            </div>
            
            <!-- Submit -->
            <div class="flex justify-end">
                <button type="submit" class="inline-flex items-center gap-2 px-8 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-xl transition shadow-lg shadow-blue-500/20 disabled:opacity-50" <?= !$allMet ? 'disabled' : '' ?>>
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                    Install K2 Pickleball
                </button>
            </div>
        </form>
        <?php endif; ?>
        
        <!-- Footer -->
        <div class="text-center mt-10 text-sm text-gray-600">
            K2 Pickleball Platform &copy; <?= date('Y') ?>
        </div>
    </div>
</body>
</html>
