-- ============================================
-- Migration 034: Booking Invoices Module
-- Tables: booking_invoices, booking_invoice_items, booking_invoice_payments
-- ============================================

CREATE TABLE IF NOT EXISTS `booking_invoices` (
    `id`                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid`                  CHAR(36) NOT NULL,
    `organization_id`       BIGINT UNSIGNED NOT NULL,
    `facility_id`           BIGINT UNSIGNED DEFAULT NULL,
    `player_id`             BIGINT UNSIGNED DEFAULT NULL,
    `created_by`            BIGINT UNSIGNED DEFAULT NULL,
    `invoice_number`        VARCHAR(50) NOT NULL,
    `customer_type`         ENUM('individual','company') NOT NULL DEFAULT 'individual',
    `customer_first_name`   VARCHAR(100) DEFAULT NULL,
    `customer_last_name`    VARCHAR(100) DEFAULT NULL,
    `customer_company`      VARCHAR(200) DEFAULT NULL,
    `customer_email`        VARCHAR(200) DEFAULT NULL,
    `customer_phone`        VARCHAR(50) DEFAULT NULL,
    `subtotal`              DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `tax_rate`              DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
    `tax_amount`            DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `discount_amount`       DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `total`                 DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `amount_paid`           DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `amount_due`            DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `currency`              VARCHAR(3) NOT NULL DEFAULT 'USD',
    `status`                ENUM('draft','sent','partially_paid','paid','overdue','cancelled','refunded') NOT NULL DEFAULT 'draft',
    `payment_type`          ENUM('full','partial') NOT NULL DEFAULT 'full',
    `issue_date`            DATE DEFAULT NULL,
    `due_date`              DATE DEFAULT NULL,
    `paid_at`               DATETIME DEFAULT NULL,
    `notes`                 TEXT DEFAULT NULL,
    `internal_notes`        TEXT DEFAULT NULL,
    `square_invoice_id`     VARCHAR(100) DEFAULT NULL,
    `auto_reminders_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_bi_uuid` (`uuid`),
    UNIQUE KEY `uk_bi_number` (`invoice_number`),
    KEY `idx_bi_org` (`organization_id`),
    KEY `idx_bi_facility` (`facility_id`),
    KEY `idx_bi_player` (`player_id`),
    KEY `idx_bi_status` (`status`),
    KEY `idx_bi_due` (`due_date`),
    CONSTRAINT `fk_bi_org` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_bi_facility` FOREIGN KEY (`facility_id`) REFERENCES `facilities` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_bi_player` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_bi_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `booking_invoice_items` (
    `id`                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `invoice_id`        BIGINT UNSIGNED NOT NULL,
    `item_type`         ENUM('session_type','class','custom') NOT NULL DEFAULT 'custom',
    `session_type_id`   BIGINT UNSIGNED DEFAULT NULL,
    `class_id`          BIGINT UNSIGNED DEFAULT NULL,
    `description`       VARCHAR(500) NOT NULL,
    `quantity`          DECIMAL(8,2) NOT NULL DEFAULT 1.00,
    `unit_price`        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `total`             DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `sort_order`        INT NOT NULL DEFAULT 0,
    `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_bii_invoice` (`invoice_id`),
    KEY `idx_bii_st` (`session_type_id`),
    CONSTRAINT `fk_bii_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `booking_invoices` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_bii_st` FOREIGN KEY (`session_type_id`) REFERENCES `session_types` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `booking_invoice_payments` (
    `id`                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid`                  CHAR(36) NOT NULL,
    `invoice_id`            BIGINT UNSIGNED NOT NULL,
    `organization_id`       BIGINT UNSIGNED NOT NULL,
    `amount`                DECIMAL(10,2) NOT NULL,
    `currency`              VARCHAR(3) NOT NULL DEFAULT 'USD',
    `payment_method`        ENUM('card','cash','check','bank_transfer','other') NOT NULL DEFAULT 'card',
    `status`                ENUM('pending','completed','failed','refunded') NOT NULL DEFAULT 'pending',
    `square_payment_id`     VARCHAR(100) DEFAULT NULL,
    `square_receipt_url`    VARCHAR(500) DEFAULT NULL,
    `notes`                 VARCHAR(500) DEFAULT NULL,
    `processed_at`          DATETIME DEFAULT NULL,
    `created_at`            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_bip_uuid` (`uuid`),
    KEY `idx_bip_invoice` (`invoice_id`),
    CONSTRAINT `fk_bip_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `booking_invoices` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_bip_org` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
